version: '3'
services:

  php:
    build: .
    volumes:
      - blog-sync:/app:nocopy
    expose:
      - 8000
    command: ./vendor/bin/sculpin generate --server --watch
    working_dir: /app
    environment:
      VIRTUAL_HOST: dmitri.docker
      VIRTUAL_PORT: 8000

volumes:
  blog-sync:
    external: true
