title: dmitri.io
author: Dmitri Lakachauskis
email: d@dmitri.io
url: https://dmitri.io

nav:
    - { url: '/', title: 'Home' }
    - { url: '/tags', title: 'Tags', priority: '1.0' }
    - { url: '/categories', title: 'Categories', priority: '1.0' }
    - { url: '/about', title: 'About', priority: '1.0' }
    - { url: '/atom.xml', title: 'Subscribe' }

link:
    website: 'https://dmitri.io'
    github:  'https://github.com/lakiboy'
    twitter: 'https://twitter.com/lakiboy'

#disqus:
#    shortname:
