title: dmitri.io
subtitle: Building apps since 2004.

full_name: Dmitri Lakachauskis

link:
    website: 'https://dmitri.io'
    github:  'https://github.com/lakiboy'
    twitter: 'https://twitter.com/lakiboy'

#disqus:
#    shortname:
