title: dmitri.io
author: Dmitri Lakachauskis
description: Blog about software development
email: 'd@dmitri.io'
url: 'https://dmitri.io'
twitter: '@lakiboy'
analytics_id: 'UA-8719868-8'

nav:
    - { url: '/', title: 'Home', priority: '0.8', changefreq: daily }
    - { url: '/tags/', title: 'Tags', priority: '1.0', changefreq: weekly }
    - { url: '/categories/', title: 'Categories', priority: '1.0', changefreq: weekly }
    - { url: '/about/', title: 'About', priority: '1.0', changefreq: weekly }
    - { url: '/atom.xml', title: 'Subscribe' }

link:
    website:  'https://dmitri.io'
    github:   'https://github.com/lakiboy'
    twitter:  'https://twitter.com/lakiboy'
    linkedin: 'https://www.linkedin.com/in/lakiboy'

#disqus:
#    shortname:
