---

- name: Create project directory
  file: state=directory name='/var/www/{{ project_name }}/current/output_prod' owner='{{ user_app }}' group='{{ user_app_group }}'

- name: Install nginx
  include_role: name=jdauphant.nginx

- name: Remove unneeded files
  file: state=absent dest='{{ item }}'
  with_items:
    - /etc/nginx/sites-available/default
    - /var/www/html/index.nginx-debian.html
    - /var/www/html
